# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

r:
  #- oldrel
  - release
  #- devel

r_packages:
  - R6
  - openssl
  - curl
  - XML
  - testthat
  - covr

r_check_args: --as-cran


matrix:
  include:
  - name: "OpenLDAP | linux"
    os: linux
    services: docker
    before_install:
    - docker pull rroemhild/test-openldap
    - docker run --privileged -d -p 389:389 rroemhild/test-openldap
  - name: "OpenLDAP | osx"
    os: osx
    services: docker
    before_install:
    - docker pull rroemhild/test-openldap
    - docker run --privileged -d -p 389:389 rroemhild/test-openldap
  - name: "OpenLDAP | windows"
    os: windows
    services: docker
    before_install:
    - docker pull rroemhild/test-openldap
    - docker run --privileged -d -p 389:389 rroemhild/test-openldap

after_script:
 - ./travis-tool.sh dump_logs
 
after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
